[interfaces] add pareto interfaces
facebookexperimental/Robyn pull request #1052
Opened 2024-09-13 05:53 UTC by alxlyj

## Project Robyn

**Summary:** We are including the interfaces (methods and data classes) for the pareto subcomponent in Python. This interface is inferred from pareto.R.  

## What is new:
- feat: New Python interfaces for pareto subcomponent. 

## Test Plan

### Class diagram
```mermaid
classDiagram
    class ParetoOptimizer {
        -MMMData input_collect
        -ModelOutputs output_models
        -ResponseCurveCalculator response_calculator
        -ImmediateCarryoverCalculator carryover_calculator
        +optimize(pareto_fronts: str, calibration_constraint: float, quiet: bool) ParetoResult
        -_prepare_data() Dict
        -_calculate_pareto_fronts(data: Dict) DataFrame
        -_calculate_response_curves(data: Dict) DataFrame
        -_prepare_plot_data(data: Dict) Dict
    }
    class ParetoResult {
        +List[str] pareto_solutions
        +int pareto_fronts
        +DataFrame result_hyp_param
        +DataFrame x_decomp_agg
        +DataFrame result_calibration
        +DataFrame media_vec_collect
        +DataFrame x_decomp_vec_collect
        +Dict plot_data_collect
        +DataFrame df_caov_pct_all
    }
    class ResponseCurveCalculator {
        -MMMData input_collect
        -ModelOutputs output_collect
        +calculate_response(select_model: str, metric_name: str, date_range: str) Dict
        -_get_hill_params(model_id: str, channel: str) Dict
        -_calculate_response_values(hill_params: Dict, spend_values: ndarray) ndarray
    }
    class ImmediateCarryoverCalculator {
        -MMMData input_collect
        -ModelOutputs output_collect
        +calculate(sol_id: str, start_date: str, end_date: str) DataFrame
        -_get_date_range(start_date: str, end_date: str) Dict
        -_calculate_saturated_dataframes(sol_id: str) Dict
        -_calculate_decomposition(sol_id: str, saturated_dfs: Dict, rolling_window: slice) Dict
        -_prepare_result_dataframe(decomp_data: Dict, start_date: str, end_date: str) DataFrame
    }
    ParetoOptimizer --> ParetoResult : produces
    ParetoOptimizer --> ResponseCurveCalculator : uses
    ParetoOptimizer --> ImmediateCarryoverCalculator : uses
    ParetoOptimizer ..> MMMData : uses
    ParetoOptimizer ..> ModelOutputs : uses
    ResponseCurveCalculator ..> MMMData : uses
    ResponseCurveCalculator ..> ModelOutputs : uses
    ImmediateCarryoverCalculator ..> MMMData : uses
    ImmediateCarryoverCalculator ..> ModelOutputs : uses
```

### Parity:
```mermaid
graph TB
    subgraph R["R Implementation"]
        R1[robyn_pareto]
        R2[pareto_front]
        R3[robyn_immcarr]
    end
    subgraph Python["Python Implementation"]
        P1[ParetoOptimizer.optimize]
        P2[ParetoOptimizer.pareto_front]
        P3[ImmediateCarryoverCalculator.calculate]
    end
    %% Connections
    R1 ---- P1
    R2 ---- P2
    R3 ---- P3
    %% New classes and data structures
    P4[ParetoResult]
    P5[ResponseCurveCalculator]
    %% Connections to new classes
    P1 --> P4
    P1 --> P5
    %% Legend
    classDef implemented fill:#90EE90,stroke:#006400;
    classDef new fill:#ADD8E6,stroke:#00008B;
    class R1,R2,R3,P1,P2,P3 implemented;
    class P4,P5 new;
    legendA[Implemented]
    legendB[New Python Classes/Structures]
    class legendA implemented;
    class legendB new;
```

-  No implementations have been included just yet with this PR so it would be lightweight to land. More rigorous testing would be included in the implementation PR.

2024-09-13 16:56 UTC, sumane81 commented on python/src/robyn/modeling/pareto/immediate_carryover_calculator.py
> +    def __init__(self, input_collect: MMMData, output_collect: ModelOutputs):
please use meaningful and relevant variable names. For example, mmmdata and model_outputs.

2024-09-13 16:57 UTC, sumane81 commented on python/src/robyn/modeling/pareto/immediate_carryover_calculator.py
> +    def _get_date_range(self, start_date: Optional[str], end_date: Optional[str]) -> Dict[str, Any]:
Recommend using datetime as input than string, which you will have to convert to datetime.

2024-09-13 16:58 UTC, sumane81 commented on python/src/robyn/modeling/pareto/immediate_carryover_calculator.py
> +            Dict[str, Any]: Dictionary containing start and end dates and indices.
Avoid using open ended dictionary. Either create complex object where it makes sense. Otherwise, use TypedDictionary

2024-09-13 17:00 UTC, sumane81 commented on python/src/robyn/modeling/pareto/pareto_optimizer.py
> +    def __init__(self, input_collect: MMMData, output_models: ModelOutputs):
Use relevant parameter names.

2024-09-13 17:01 UTC, sumane81 commented on python/src/robyn/modeling/pareto/pareto_optimizer.py
> +        quiet: bool = False,
Let's remove quiet. It should be managed at logger level.

2024-09-13 17:02 UTC, sumane81 commented on python/src/robyn/modeling/pareto/pareto_optimizer.py
> +    def _prepare_data(self) -> Dict[str, pd.DataFrame]:
It's unclear on what this method does. Can we be specific on what preparations it does?

2024-09-13 17:03 UTC, sumane81 commented on python/src/robyn/modeling/pareto/pareto_utils.py
This doesn't seem to be a class? if functions are self independent then you can use class and define these methods as static methods.

2024-09-13 17:04 UTC, sumane81 commented on python/src/robyn/modeling/pareto/__init__.py
Do we need this file here?

2024-09-13 17:05 UTC, sumane81 commented on python/src/robyn/modeling/pareto/immediate_carryover_calculator.py
> +from typing import Optional, Dict, Any
Let's not use Any. If you absolutely need to, please justify.

2024-09-13 17:05 UTC, sumane81 commented on python/src/robyn/modeling/pareto/immediate_carryover_calculator.py
> +        self.input_collect = input_collect
Same as above, no input_collect, output_collect.

2024-09-13 17:06 UTC, sumane81 commented on python/src/robyn/modeling/pareto/immediate_carryover_calculator.py
> +            Dict[str, Any]: Dictionary containing start and end dates and indices.
Also, let's not use Any if possible.

2024-09-13 17:06 UTC, sumane81 commented on python/src/robyn/modeling/pareto/pareto_optimizer.py
> +from typing import List, Dict, Any, Optional
Let's not use Any, if possible.

2024-09-13 17:07 UTC, sumane81 commented on python/src/robyn/modeling/pareto/pareto_optimizer.py
> +from robyn.modeling.pareto.pareto_utils import pareto_front
pareto_utils should be class

2024-09-13 17:08 UTC, sumane81 commented on python/src/robyn/modeling/pareto/pareto_optimizer.py
> +        input_collect (MMMData): Input data for the marketing mix model.
use mmm_data or mmmdata as variable name. Let's be consistent with other parts of the codebase

2024-09-13 17:08 UTC, sumane81 commented on python/src/robyn/modeling/pareto/pareto_optimizer.py
> +        output_models (ModelOutputs): Output data from the model runs.
model_outputs instead of output_models, just to be consistent

2024-09-13 17:10 UTC, sumane81 requested changes
Mostly nits; but strongly suggest addressing them.

2024-09-17 20:39 UTC, alxlyj commented
### pareto_optimizer.py
1. We've removed the use of Any type where possible, using more specific types instead.
1. pareto_utils is now a class (ParetoUtils) rather than a module with standalone functions.
1. We've used mmm_data consistently as the variable name for the input data.
1. We've changed output_models to model_outputs for consistency.
1. We've renamed input_collect to mmm_data for clarity.
1. We've removed the quiet parameter, assuming logging will be handled at a different level.
1. We've renamed _prepare_data to _aggregate_model_data and provided a more detailed description of what it does.
1. We've added comprehensive docstrings for the class and all methods, explaining their purpose, parameters, and return values in detail.

2024-09-17 21:04 UTC, alxlyj commented
Updated diagrams.

2024-09-18 22:25 UTC, sumane81 approved these changes

2024-09-19 16:18 UTC, merged