[interfaces] add transformation Python interfaces
facebookexperimental/Robyn pull request #1053
Opened 2024-09-13 06:04 UTC by alxlyj

## Project Robyn

**Depends on https://github.com/facebookexperimental/Robyn/pull/1050**

**Summary:** We are including the interfaces (methods and data classes) for the transformation subcomponent in Python. This interface is inferred from transformations.R.  

## What is new:
- feat: New Python interfaces for transformation subcomponent. 

## Test Plan

### Class diagram
```mermaid
classDiagram
    class Transformations {
        +mic_men(x: np.ndarray, Vmax: float, Km: float, reverse: bool) np.ndarray$
        +adstock_geometric(x: np.ndarray, theta: float) Dict[str, Any]$
        +adstock_weibull(x: np.ndarray, shape: float, scale: float, windlen: int, type: str) Dict[str, Any]$
        +transform_adstock(x: np.ndarray, adstock: AdstockType, theta: float, shape: float, scale: float, windlen: int) Dict[str, Any]$
        +saturation_hill(x: np.ndarray, alpha: float, gamma: float, x_marginal: np.ndarray) np.ndarray$
        +run_transformations(input_collect: Dict[str, Any], hyperparameters: Dict[str, Any]) Dict[str, Any]$
        -_weibull_cdf(x: np.ndarray, shape: float, scale: float) np.ndarray$
        -_weibull_pdf(x: np.ndarray, shape: float, scale: float) np.ndarray$
        -_normalize(x: np.ndarray) np.ndarray$
    }
    class TransformationVisualizer {
        +plot_adstock(plot: bool) Optional[Tuple[plt.Figure, plt.Figure]]$
        +plot_saturation(plot: bool) Optional[Tuple[plt.Figure, plt.Figure]]$
    }
    class AdstockType {
        <<enumeration>>
        GEOMETRIC
        WEIBULL_CDF
        WEIBULL_PDF
    }
    Transformations ..> AdstockType : uses
    TransformationVisualizer ..> Transformations : uses for data
```

### Parity:
```mermaid
graph TB
    subgraph R["R Implementation"]
        R1[mic_men]
        R2[adstock_geometric]
        R3[adstock_weibull]
        R4[transform_adstock]
        R5[saturation_hill]
        R6[plot_adstock]
        R7[plot_saturation]
        R8[run_transformations]
    end
    subgraph Python["Python Implementation"]
        P1[Transformations.mic_men]
        P2[Transformations.adstock_geometric]
        P3[Transformations.adstock_weibull]
        P4[Transformations.transform_adstock]
        P5[Transformations.saturation_hill]
        P6[TransformationVisualizer.plot_adstock]
        P7[TransformationVisualizer.plot_saturation]
        P8[Transformations.run_transformations]
    end
    %% Connections
    R1 ---- P1
    R2 ---- P2
    R3 ---- P3
    R4 ---- P4
    R5 ---- P5
    R6 ---- P6
    R7 ---- P7
    R8 ---- P8
    %% New structures
    P9[AdstockType Enum]
    %% Connections to new structures
    P4 --> P9
    %% Legend
    classDef implemented fill:#90EE90,stroke:#006400;
    classDef new fill:#ADD8E6,stroke:#00008B;
    class R1,R2,R3,R4,R5,R6,R7,R8,P1,P2,P3,P4,P5,P6,P7,P8 implemented;
    class P9 new;
    legendA[Implemented]
    legendB[New Python Structures]
    class legendA implemented;
    class legendB new;```

-  No implementations have been included just yet with this PR so it would be lightweight to land. More rigorous testing would be included in the implementation PR.

2024-09-13 17:23 UTC, sumane81 commented on python/src/robyn/modeling/transformations/__init__.py
Let's remove this until we have something to add here

2024-09-13 17:25 UTC, sumane81 commented on python/src/robyn/modeling/transformations/transformations.py
> +from typing import List, Dict, Any, Tuple, Optional
Let's not use Any, if possible

2024-09-13 17:27 UTC, sumane81 commented on python/src/robyn/modeling/transformations/transformations.py
> +class Transformations:
All of the methods are static in here. It is not clean object oriented class. Let's use input data as class variables that then is used by methods in this class

2024-09-13 17:28 UTC, sumane81 commented on python/src/robyn/modeling/transformations/transformations.py
> +    def mic_men(x: np.ndarray, Vmax: float, Km: float, reverse: bool = False) -> np.ndarray:
1. x is input data that will be common for most methods. Let's make that instance variable
2. Use meaningful variable name. "x" isn't meaningful variable name,

2024-09-13 17:30 UTC, sumane81 commented on python/src/robyn/visualization/transformation_visualization.py
> +class TransformationVisualizer:
Explore instance variable and make it a clean Class if possible.

2024-09-13 17:31 UTC, sumane81 commented on python/src/robyn/visualization/transformation_visualization.py
> +    def plot_adstock(plot: bool = True) -> Optional[Tuple[plt.Figure, plt.Figure]]:
plot method, taking plot=true/false doesn't make sense. Is this creating a plot plt.Figure vs actually printing it?

2024-09-13 17:31 UTC, sumane81 requested changes
added comments

2024-09-17 18:29 UTC, alxlyj commented on python/src/robyn/modeling/transformations/transformations.py
> +from typing import List, Dict, Any, Tuple, Optional
refactored code.

2024-09-17 18:43 UTC, alxlyj commented
TransformationVisualizer: 

1. It now uses instance variables (self.adstock_figures and self.saturation_figures) to store the generated plots.

1. The plot parameter has been removed. Instead, separate methods are provided for creating, retrieving, displaying, and saving plots.

1. The class now has a clear separation between plot creation (create_adstock_plots, create_saturation_plots) and plot retrieval (get_adstock_plots, get_saturation_plots).

1. New methods have been added for displaying (display_adstock_plots, display_saturation_plots) and saving (save_adstock_plots, save_saturation_plots) the plots.

1. The plot creation methods are called lazily when the plots are first requested, ensuring they're only created when needed.

2024-09-17 18:46 UTC, alxlyj commented
transformations.py:

1. We've replaced input_data with time_series_data, which more accurately describes the nature of the data these methods are operating on.

1. The Transformation class now takes an MMMData object and a media_channel name as input. We've added a _get_channel_data method to extract the relevant data for the specified media channel from the MMMData object.

1. The methods that operate on the instance's data (michaelis_menten, adstock_geometric, adstock_weibull, transform_adstock, and saturation_hill) remain as instance methods. These methods use the channel_data attribute of the class instance.

1. The utility methods that don't depend on the instance's state (weibull_cdf, weibull_pdf, and normalize) are kept as static methods. These methods can be used without creating an instance of the Transformation class.

2024-09-17 19:11 UTC, sumane81 approved these changes

2024-09-17 19:19 UTC, merged