update: feature engineering unit tests
facebookexperimental/Robyn pull request #1086
Opened 2024-10-24 03:12 UTC by alxlyj

## Project Robyn

### Summary

- Update feature eng unit test.

### Test Plan

2024-10-24 04:44 UTC, sumane81 requested changes

2024-10-24 04:44 UTC, sumane81 commented on python/tests/src/robyn/modeling/test_feature_engineering.py
1. Code coverage is at 70% compared to 74% from earlier tests. 
2. Can you remove the src folder from the path?

2024-10-24 04:44 UTC, sumane81 commented on python/tests/src/robyn/modeling/test_feature_engineering.py
> +        self.mmm_data = MagicMock(spec=MMMData)
I preferred using simulated data than letting unit test mock create high level mock data.

2024-10-24 04:44 UTC, sumane81 commented on python/tests/src/robyn/modeling/test_feature_engineering.py
> +        self.assertTrue(hasattr(result, "dt_mod"))
Just having the attributes is good enough test?

2024-10-24 04:44 UTC, sumane81 commented on python/spec/src/robyn/modeling/feature_engineering.md
can you change spec folder name to docs? Also, remove src folder from the path

2024-11-05 21:16 UTC, alxlyj commented
see https://github.com/facebookexperimental/Robyn/pull/1110

2024-11-05 21:16 UTC, closed without merging