[feature] add allocator
facebookexperimental/Robyn pull request #1088
Opened 2024-10-24 21:47 UTC by alxlyj

## Pending

2024-10-30 19:33 UTC, sumane81 requested changes
Mostly ;nits but would like it if you can address them.

2024-10-30 19:33 UTC, sumane81 commented on python/src/robyn/allocator/entities/enums.py
> +class UseCase(str, Enum):
nit; can we use more specific name for the enum? AllocatorUseCase etc?

2024-10-31 00:25 UTC, alxlyj commented on python/src/robyn/visualization/allocator_visualizer.py
> +class AllocationPlotter:
I think it will probably make sense to shift this as part of the visualizer PR's refactor since that will address base_viz.

2024-10-31 04:47 UTC, sumane81 approved these changes
Good example of well structured, modular code that will be easy to read and maintain.

2024-10-31 05:22 UTC, merged