One pager interface
facebookexperimental/Robyn pull request #1096
Opened 2024-10-29 19:45 UTC by sumalreddy17

Add One Pager Plot class structure and method signatures

Introduces core class architecture for marketing analytics visualization
with comprehensive method signatures for all plot types.

Key components:
- PlotData dataclass for standardized data handling
- MarketingOnePager class with plot generation methods
- Method signatures for 8 distinct visualization types

2024-10-29 19:58 UTC, dhavalpatel624624 commented
Let's avoid the use of both pyplot and go. Lets pick one over the other. Also, I see some files have Any datatypes, lets get those specified. Can we also add the  `PlotData`  in the constructor of each individual visualizer files and remove it from underlying methods if it makes sense. Then, make sure you instantiate each of the visualizers and call the functions in `generate_onepager` instead of the functions directly.

2024-10-29 21:20 UTC, sumane81 commented on python/src/robyn/visualization/plot_data.py
You shouldn't need to define new data entity in visualizer module. Input data for visualizer should directly come from component. For example - ParetoVisualizer should take ParetoResult.

2024-10-31 17:08 UTC, sumalreddy17 commented on python/src/robyn/visualization/onepager_visualizer.py
> +        self.pareto_result = pareto_result
This can be moved to BaseVisualizer.

2024-10-31 18:58 UTC, sumane81 requested changes
Comments added

2024-10-31 19:14 UTC, dhavalpatel624624 approved these changes

2024-10-31 19:15 UTC, dhavalpatel624624 commented
Looks good, thanks for making all the changes! :)

2024-10-31 22:34 UTC, sumane81 commented on python/src/robyn/visualization/input_visualizer.py
input visualizer is vague name. Can we make it more specific?

2024-10-31 23:04 UTC, sumalreddy17 commented on python/src/robyn/visualization/input_visualizer.py
How about media_response_visualizer?

2024-10-31 23:47 UTC, sumane81 commented on python/src/robyn/visualization/robyn_visualizer.py
What is this file for? Can you delete it if not needed?

2024-10-31 23:49 UTC, sumalreddy17 commented on python/src/robyn/visualization/robyn_visualizer.py
Offline decision to clean up in a different PR

2024-10-31 23:49 UTC, sumane81 approved these changes
Some clean up is needed but that will come in separate PR.

2024-10-31 23:51 UTC, merged