Test/unit tests pareto optimizer
facebookexperimental/Robyn pull request #1109
Opened 2024-11-05 18:40 UTC by Marco-Premier

## Project Robyn

Add tests for pareto_optimizer

2024-11-05 20:24 UTC, dhavalpatel624624 commented
Can you add the pytest run results? Also are we going to be using the unittest library or pytest? We should standardize the libraries we use across all unit tests. Also, I think this needs a rebase on robynpy_release (you are out of date currently)

Also, are there any common best practices that should be followed here for generating mock data. I feel like there is a lot of redundancy in how the data is mocked for each function

2024-11-06 10:59 UTC, Marco-Premier commented
> Can you add the pytest run results? Also are we going to be using the unittest library or pytest? We should standardize the libraries we use across all unit tests. Also, I think this needs a rebase on robynpy_release (you are out of date currently)
> 
> Also, are there any common best practices that should be followed here for generating mock data. I feel like there is a lot of redundancy in how the data is mocked for each function

Goog points.
I'm happy to use pytest.
I refactor the code to use pytest and to group common mock data setup using pytest fixture.
Also I noticed that in tests where we aim to use pytest we still depend on unittest framework, eg. for `patch`, `MagicMock` etc...

We may consider using the `pytest-mock` instead.
I'd do that on a separate PR

2024-11-07 19:02 UTC, dhavalpatel624624 commented
Still waiting for a rebase on this

2024-11-07 19:04 UTC, dhavalpatel624624 requested changes
need to remove pareto_optimizer and response_curve file changes. A rebase should fix it :)

2025-03-05 03:06 UTC, closed without merging